url: http://fgo.cz
baseurl: ""

title: Family Gospel Ostrava
email: qadim@centrum.cz
description: "Oficiální web komunitního gospelového sboru Family Gospel Ostrava (FGO)."

sbor:
- name: Radim Raszka
  pic: raszka_radim
- name: Veronika Raszková
  pic: raszkova_veronika
- name: Katka Vopalecká
  pic: vopalecka_katka
- name: Radim Toman
  pic: toman_radim
- name: Ethel Tomanová
  pic: tomanova_ethel
- name: Karin Janiczková
  pic: janiczkova_karin
- name: Kateřina Vereš
  pic: veres_katerina

kapela:
- name: Martin Janiczek
  pic: janiczek_martin
  position: kapelník, klávesy
- name: Eliška Burdová
  pic: burdova_eliska
  position: klávesy
- name: Jan Vereš
  pic: veres_jan
  position: bicí
- name: Kamila Holmanová
  pic: holmanova_kamila
  position: basová kytara
- name: Casey Long
  pic: long_casey
  position: akustická kytara
- name: Jan Kubenka
  pic: kubenka_jan
  position: elektrická kytara
- name: Jířa Marušáková
  pic: marusakova_jira
  position: housle

byvali:
- name: Martin Bazala
  pic: bazala_martin
  position: sbormistr
- name: Pavel Kubiczek
  pic: kubiczek_pavel
  position: klávesy
- name: David Horváth
  pic: horvath_david
  position: klávesy, akustická kytara

deti:
- name: Dana a Lenka Verešová
  pic: veresova_dana_a_lenka
- name: Petra Gruszková
  pic: gruszkova_petra

social:
  - title: facebook
    url: https://www.facebook.com/groups/604262332991737/

address:
  - line: Kulturní centrum Cooltour
  - line: Černá louka 3188
  - line: 70200 Ostrava - Moravská Ostrava

markdown: kramdown
permalink: pretty
